Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -2,16 +2,8 @@ name: Build
 
 on:
   workflow_dispatch:
-  push:
-    branches:
-      - master
-    paths-ignore:
-      - '**/*.md'
-      - '**/*.yml'      
-      - '.gitignore'
-      - '.dockerignore'
-      - '.github/**'
-      - '.github/workflows/**'
+  schedule:
+    - cron: '0 0 * * *'
 
 concurrency:
   group: build
@@ -23,18 +15,60 @@ jobs:
     runs-on: ubuntu-latest
     permissions:
       packages: write
-      contents: read    
+      contents: read
     steps:
       - 
+        name: Run graphql query to get tag
+        uses: octokit/graphql-action@v2.x
+        id: latest_tag
+        with:
+          variables: |
+            repo: bitcoin
+            owner: bitcoin
+          query: |
+            query tag($owner: String!, $repo: String!) {
+              repository(owner: $owner, name: $repo) {
+                refs(refPrefix: "refs/tags/", last: 1, orderBy: {field: TAG_COMMIT_DATE, direction: ASC}) {
+                  edges {
+                    node {
+                      name
+               } } } } }
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - 
+        name: Parse tag from query output
+        run: |
+          #!/bin/bash
+          latest_tag=$(echo '${{ steps.latest_tag.outputs.data }}' | jq '.repository.refs.edges[][].name' -r)
+          [ -z "$latest_tag" ] && echo "Tag not found!" && exit 1
+          [[ "$latest_tag" = v* ]] && latest_tag="${latest_tag:1}"
+          echo "Found tag: \"${latest_tag}\""
+          echo "latest_tag=$latest_tag" >> $GITHUB_ENV
+      - 
+        name: Check if the tag exists in DockerHub
+        id: check-tag
+        run: |
+          #!/bin/bash
+          [ -z "${{ env.latest_tag }}" ] && echo "exists=true" >> $GITHUB_ENV && exit 0
+          dockerhub_tags=$(curl -s https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_REPO }}/tags | jq -r '.results[].name')
+          if echo "${dockerhub_tags}" | grep -qx "${{ env.latest_tag }}"; then
+            echo "exists=true" >> $GITHUB_ENV
+          else
+            echo "exists=false" >> $GITHUB_ENV
+          fi
+      - 
         name: Set up Docker Buildx
+        if: env.exists == 'false'
         uses: docker/setup-buildx-action@v3
       -
         name: Checkout
+        if: env.exists == 'false'
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
       -
         name: Prepare Docker build
+        if: env.exists == 'false'
         id: prepare
         run: |
           
@@ -57,12 +91,14 @@ jobs:
           echo "build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
       -
         name: Login into Docker Hub
+        if: env.exists == 'false'
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKER_USER }}
           password: ${{ secrets.DOCKER_TOKEN }}
       -
         name: Login to GitHub Container Registry
+        if: env.exists == 'false'
         uses: docker/login-action@v3
         with:
           registry: ghcr.io
@@ -70,6 +106,7 @@ jobs:
           password: ${{ secrets.GITHUB_TOKEN }}
       - 
         name: Build Docker image
+        if: env.exists == 'false'
         run: |
         
           TAGS=(${{ steps.prepare.outputs.tags }})
@@ -87,10 +124,12 @@ jobs:
             $(printf "%s" "${TAGS[@]/#/ --tag }" ) .
       -
         name: Clear Docker credentials
+        if: env.exists == 'false'
         run: |
           rm -f ${HOME}/.docker/config.json
       -
         name: Create a release
+        if: env.exists == 'false'
         uses: action-pack/github-release@v2
         env:
           GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
@@ -99,6 +138,7 @@ jobs:
           title: "v${{ steps.prepare.outputs.version }}"
       -
        name: Send mail
+       if: env.exists == 'false'
        uses: dawidd6/action-send-mail@v3
        with:
          to: ${{secrets.MAILTO}}
